name = "OutlierDetectionPy"
uuid = "2449c660-d36c-460e-a68b-92ab3c865b3e"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
